[handbooks]
logLevel = "info"

[database]
host = "localhost"
port = 5431
user = "postgres"
password = "admin21"
name = "handbooks"
sslmode = "disable"

[server]
host = "localhost"
port = 3001
readTimeout = "10s"
writeTimeout = "30s"
idleTimeout = "60s"
