[handbooks]
logLevel = 1

[database]
host = "postgres"
port = 5432
sslmode = "disable"

[server]
host = "localhost"
port = 3001
readTimeout = "10s"
writeTimeout = "30s"
idleTimeout = "60s"

[redis]
addr = "redis:6379"
db = 0
refreshTokenTTL = "168h"
accessTokenTTL = "24h"

[jwt]
issuer = "handbooks-server"
audience = "handbooks-client"
